/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BattleswapsHook } from "./BattleswapsHook";
export type { BattleswapsRouter } from "./BattleswapsRouter";
export * as factories from "./factories";
export { BattleswapsHook__factory } from "./factories/BattleswapsHook__factory";
export { BattleswapsRouter__factory } from "./factories/BattleswapsRouter__factory";
